force-app/main/default/objects/Account/fields/Number_Of_Calls_Yesterday__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Calls_Yesterday__c</fullName>
    <label>Number Of Calls Yesterday</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Call__c/Call__c.object-meta.xml
<CustomObject>
    <label>通话历史</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Call</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call__c/fields/TextTest__c.field-meta.xml
<CustomField>
    <fullName>TextTest__c</fullName>
    <label>文本测试字段(元数据修改为长文本区)</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CallBatch.cls
global class CallBatch implements Database.Batchable<sObject> {
    public String query;
    
    global CallBatch() 
    {
        this.query = 'select Id,Account__c,TextTest__c from Call__c where createdDate = today';
    }

    global Database.QueryLocator start(Database.BatchableContext bc) 
    {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, list<Sobject> scope) 
    {
        System.debug('=======execute方法执行');
        Map<Id,Integer> map_sum = new Map<Id,Integer>();      
        for (Call__c call: (List<Call__c>) scope) {
            //存在的情况
            if(map_sum.containsKey(call.Account__c))
            {
                map_sum.put(call.Account__c, map_sum.get(call.Account__c)+1);
            }
            else//不存在的情况
            {
                map_sum.put(call.Account__c, 1);
                System.debug(call.TextTest__c);
            }
        }
        System.debug('=======查询执行结束');
        Set<Id> set_Id = map_sum.keySet();
        List<Account> accountList = new List<Account>();
        for (Id strId :set_Id ) {
            Account acc = new Account();
            acc.Id = strId;
            acc.Number_Of_Calls_Yesterday__c = map_sum.get(strId);
            accountList.add(acc);
        }
        update accountList;
    }

    global void finish(Database.BatchableContext BC) 
    {
        
    }
}